development:
  adapter: postgresql
  database: loomio_development

production:
  <<: *default
  url: <%= ENV['postgresql://admin:6UdSkHN5UN3tnhtHyuWHRCCJ5aI4S9AO@dpg-ctcn6lrtq21c73ft5b60-a/aurjobssourcing1'] %>


test:
  adapter: postgresql
  database: loomio_test
