name: Generate Master Key

on:
  push:
    branches:
      - main  # Change to the branch you use for production

jobs:
  generate-master-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: |
          bundle install

      - name: Generate Master Key
        run: |
          # Generate a new master key using Rails secret command
          rails secret > config/master.key
          git add config/master.key
          git commit -m "Add generated master.key"
          git push origin main

      - name: Push changes to GitHub
        run: |
          git push origin main
